version: "3.9"

services:
  askmeanything:
    build: .
    container_name: askmeanything
    ports:
      - "1337:5000"
      - "2222:22"
    environment:
      - FLAG=130d44e1376493212c187abd3047c373
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3500M
    restart: unless-stopped
